---
steps:
  - name: ':docker: Build'
    agents:
      queue: builder
    plugins:
      docker-compose:
        build: athenaeum
        image-repository: us.gcr.io/pg-shared-v1/athenaeum
        image-name: $BUILDKITE_BUILD_NUMBER

  - wait

  - name: 'Upload MainNav to Staging :s3:'
    command: bin/deploy_nav_staging
    agents:
      queue: builder
    plugins:
      docker-compose:
        run: athenaeum

  - wait

  - name: 'Upload MainNav to Rebrand :s3:'
    command: bin/deploy_nav_rebrand
    branches: 'rebrand'
    agents:
      queue: builder
    plugins:
      docker-compose:
        run: athenaeum

  - wait

  - name: 'Upload Footer to Staging :s3:'
    command: bin/deploy_footer_staging
    agents:
      queue: builder
    plugins:
      docker-compose:
        run: athenaeum

  - wait


  - name: 'Upload Footer to Rebrand :s3:'
    command: bin/deploy_footer_rebrand
    agents:
      queue: builder
    plugins:
      docker-compose:
        run: athenaeum

  - wait

  - block: 'Deploy git:master MainNav to Production?'
    prompt: "Please review and approve your changes at: http://rcl.policygenius.com/staging/main_nav/index.html"
    branches: 'master'

  - name: 'Upload MainNav to Production :s3:'
    branches: 'master'
    command: bin/deploy_nav_production
    agents:
      queue: builder
    plugins:
      docker-compose:
        run: athenaeum
