steps:
  - name: ':docker: Build'
    agents:
      queue: builder
    plugins:
      docker-compose:
        build: athenaeum
        image-repository: us.gcr.io/pg-shared-v1/athenaeum
        image-name: $BUILDKITE_BUILD_NUMBER

  - wait

  - name: ':scsslint:'
    command: yarn lint
    agents:
      queue: runner
    plugins:
      docker-compose:
        run: athenaeum

  - name: ':jest:'
    command: yarn test --coverage
    agents:
      queue: runner
    plugins:
      docker-compose:
        run: athenaeum
    artifact_paths:
      - "coverage/lcov.info"

  - wait

  - name: ':sonar-scanner:'
    # branches: 'v9.0.0'
    command: /usr/bin/scan-sonar
    agents:
      queue: runner
    plugins:
      docker-compose:
        run: sonar

  - name: ':speaker: :sparkle: Automated Code Review'
    branches: "!v9.0.0 !hotfix/*"
    command: /usr/bin/scan-pullrequest
    agents:
      queue: runner
    plugins:
      docker-compose:
        run: sonar

  - wait

  - block: 'Trigger deploy/publish'
    branches: 'v9.0.0'
    prompt: 'Choose a version bump'
    fields:
    - select: 'Increment'
      key: 'bump-size'
      hint: "MAJOR: incompatible API changes // MINOR: add backwards-compatible functionality // PATCH: backwards-compatible bug fixes"
      required: true
      options:
        - label: 'Major -- Please avoid major bumps'
          value: 'major'
        - label: 'Minor'
          value: 'minor'
        - label: 'Patch'
          value: 'patch'

  - block: "Trigger custom deploy for current version"
    branches: '!v9.0.0'

  - name: ':npm:'
    command: bin/build
    agents:
      queue: builder
    plugins:
      docker-compose:
        run: athenaeum
    artifact_paths:
      - styleguide/**/*

  - wait

  - name: ':rocket: :gcloud:'
    command: bin/deploy
    agents:
      queue: sandbox

  - wait

  - name: ':rocket: :octocat:'
    command: bin/commit-tag
    branches: 'v9.0.0'
    agents:
      queue: builder

