---
steps:
  - name: ':docker: Build'
    agents:
      queue: builder
    plugins:
      docker-compose:
        build: athenaeum
        image-repository: us.gcr.io/pg-shared-v1/athenaeum
        image-name: $BUILDKITE_BUILD_NUMBER

  - wait

  - name: ':scsslint:'
    command: yarn lint
    agents:
      queue: runner
    plugins:
      docker-compose:
        run: athenaeum

  # Run tests with coverage if not a hotfix
  - name: ':jest:'
    branches: "!hotfix/*"
    command: bin/test
    agents:
      queue: runner
    plugins:
      docker-compose:
        run: athenaeum
    artifact_paths:
      - "coverage/lcov.info"

  # Run tests without coverage if this is a hotfix
  # This is necessary for builds triggered by PR merges to master
  - name: ':jest:'
    branches: "hotfix/*"
    command: bin/test hotfix
    agents:
      queue: runner
    plugins:
      docker-compose:
        run: athenaeum

  - wait

  - name: ':sonar-scanner:'
    branches: master
    command: bin/sonar
    agents:
      queue: runner
    plugins:
      docker-compose:
        run: athenaeum

  - name: ':speaker: :sparkle: Automated Code Review'
    branches: "!master !hotfix/*"
    command: bin/scan-pullrequest
    agents:
      queue: runner
    plugins:
      docker-compose:
        run: athenaeum

  - wait

  - block: 'Trigger deploy/publish'
    branches: 'master'
    prompt: 'Choose a version bump'
    fields:
    - select: 'Increment'
      key: 'bump-size'
      hint: "MAJOR: incompatible API changes // MINOR: add backwards-compatible functionality // PATCH: backwards-compatible bug fixes"
      required: true
      options:
        - label: 'Major -- Please avoid major bumps'
          value: 'major'
        - label: 'Minor'
          value: 'minor'
        - label: 'Patch'
          value: 'patch'

  - block: "Trigger custom deploy for current version"
    branches: '!master'

  - name: ':npm:'
    command: bin/build
    agents:
      queue: builder
    plugins:
      docker-compose:
        run: athenaeum
    artifact_paths:
      - styleguide/**/*

  - wait

  - name: ':rocket: :gcloud:'
    command: bin/deploy
    agents:
      queue: sandbox

  - wait

  - name: ':rocket: :octocat:'
    command: bin/commit-tag
    branches: master
    agents:
      queue: builder

